name: galleryapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.4.0
  faker: ^2.2.0
  google_fonts: ^4.0.3
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  provider: ^6.1.2
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  image_picker: ^1.0.4
  shared_preferences: ^2.5.2
  flutter_dotenv: ^5.2.1
  file_picker: ^8.3.3
  cloud_firestore: ^5.6.3
  permission_handler: ^11.3.1
  cloudinary_public: ^0.23.1
  http: ^0.13.5
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/galeri.png
    - assets/galeri.png
    - assets/irpl.png
    - assets/pictyou_icon.png
    - assets/pictapp.png
    - assets/profil_default.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/pictapp.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/pictapp.png"
